### ISSUE TITLE
Issue when installing 

### ISSUE THREAD

**Issue by rossiluis22** [olivierjan/OctoPrint-PSUControl-Meross#1]
Hi, i tried several times to install the plug-in but when is “Done” the upper right message says “Installed: Unknown “ and after reboot there is no plug-in, do i need to do something else?

![2AA86104-1AF6-4A64-81A6-A746CD14F2F2](https://user-images.githubusercontent.com/15603808/132068249-84e21d77-a74d-4636-a476-9b92b11b265c.jpeg)

**Comment by olivierjan** [comment]
Hi, 
The "Install: Unknown" is a known bug, I need to fix it. Still this shouldn't prevent installation to complete. 
I just tried installing on a fresh Octoprint Install and didn't face any issue. 
Can you confirm that you have installed PSU Control and restarted before installing the PSU Control - Meross plug-in ? 
Could you share on which platform you're running Octoprint and if possible the OctoPrint log file ?

**Comment by rossiluis22** [comment]
Hi again :)

I'm using octoprint docker image Version 1.6.1, tried to recreate the whole docker and install like you mentioned first PSU Control then the Meross plugin, it didn't worked, I think from what i read from the logs i'm missing some libraries. 


[octoprint.log](https://github.com/olivierjan/OctoPrint-PSUControl-Meross/files/7111356/octoprint.log)

**Comment by olivierjan** [comment]
I just tried to replicate the issue without success. 

1. Installed docker
2. Followed the procedure here: https://hub.docker.com/r/octoprint/octoprint
3. Configured Octoprint
4. Installed PSU Control
5. Restarted Octoprint
6. Installed PSU Control-Meross (from plugin manager using URL: https://github.com/olivierjan/OctoPrint-PSUControl-Meross/archive/master.zip)
7. Restarted Octoprint
8. Configured PSU Control - Meross plugin
9. Restarted Octoprint

Clearly your logs shows an issue with missing library meross-iot, but it's normally installed with the plug-in. 
There might be a conflict somewhere: Could you also share the plugin manager log (plugin_pluginmanager_console.log) ? 

Regards,

**Comment by rossiluis22** [comment]
I tried in a fresh docker installation and following your steps but still not working :(, I 'll attach the logs. 

PS: I really appreciate your time to help me :)
[octoprint (1).log](https://github.com/olivierjan/OctoPrint-PSUControl-Meross/files/7112229/octoprint.1.log)
[plugin_pluginmanager_console (1).log](https://github.com/olivierjan/OctoPrint-PSUControl-Meross/files/7112230/plugin_pluginmanager_console.1.log)

**Comment by olivierjan** [comment]
So I tried to replicate on a different machine today (a PC), but without success. 
Looking at your logs, you're running on an ARM platform (RPI3 ?) while I've been testing Docker images on AMD64 (PC and Mac) and directly (no Docker) on RPI 3 with latest Octopi image. 

What I can see from the logs is a problem with FFI library not being present on  your system (you can confirm with a `apt list | grep ffi` inside the container). This is not normal, but I found a few reference of similar issues when using Python Docker image for ARM v7. 
If the library is not installed, you can try installing it manually inside the container with following command : 
`apt install libffi-dev`

Anyway, if you're actually running on a Raspberry Pi it might be better to use an OctoPi image instead of a Docker container.

**Comment by rossiluis22** [comment]
I ended up installing OctoPi as you mentioned a it did work! thank you so much for your help :)
